### ISSUE TITLE
Does this work with mi band 3?

### ISSUE THREAD

**Issue by rayavarapuvikram1** [NoRoboto/mi-band2-scripts#1]

**Comment by NoRoboto** [comment]
HI! @rayavarapuvikram1,

This implementation is based on the following package https://github.com/vshymanskyy/miband-js Unfortunately this project has not been updated in a couple of years so I do not think it will work for my band v3. But Not everything is lost, it seems works
  https://github.com/vshymanskyy/miband-js/issues/20
